### Signup a user

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "full_name" : "Kenedy maina",
    "email": "kenedy@gmail.com",
    "password": "Boomplay@1"
}


### Login a user

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "kennynet66@gmail.com",
    "password": "Boomplay@1"
}

### Get all users

GET http://localhost:3000/user/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXRhaWxzIjp7ImlkIjoiYTkxNmUzMzQtY2JlOC00M2RhLWJmNmQtMGViNzM2YmUyZmMwIiwiZnVsbF9uYW1lIjoiS2VuZWR5IG1haW5hIiwiZW1haWwiOiJrZW5ueW5ldDY2QGdtYWlsLmNvbSIsInByb2ZpbGVfaW1nIjoiaHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMC5nc3RhdGljLmNvbS9pbWFnZXM_cT10Ym46QU5kOUdjVGtZdnE3eldlWWdmMnlEeFBSRXhCay1sNGhoQ3prNkZ5aFdBJnVzcXA9Q0FVIiwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTcwODg0MzQ4OSwiZXhwIjoxNzA4OTQ3MTY5fQ.hGAyUUJdxXdPCqVW7euK44hUBusLtjOnl4G5vqn9XeM

### Get user by id
GET http://localhost:3000/user/a916e334-cbe8-43da-bf6d-0eb736be2fc0
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXRhaWxzIjp7ImlkIjoiYTkxNmUzMzQtY2JlOC00M2RhLWJmNmQtMGViNzM2YmUyZmMwIiwiZnVsbF9uYW1lIjoiYTkxNmUzMzQtY2JlOC00M2RhLWJmNmQtMGViNzM2YmUyZmMwIiwiZW1haWwiOiJrZW5ueW5ldDY2QGdtYWlsLmNvbSJ9LCJpYXQiOjE3MDgyOTU3OTgsImV4cCI6MTcwODM5OTQ3OH0.AfLmRLuJZLzm-Zb56oCWcevwsv5K5CbOgI4eXRw8Nyc

### Deactivate a user account
PUT http://localhost:3000/user/deactivate/38316fae-8574-426c-be71-56de9f85b170
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXRhaWxzIjp7ImlkIjoiYTkxNmUzMzQtY2JlOC00M2RhLWJmNmQtMGViNzM2YmUyZmMwIiwiZnVsbF9uYW1lIjoiYTkxNmUzMzQtY2JlOC00M2RhLWJmNmQtMGViNzM2YmUyZmMwIiwiZW1haWwiOiJrZW5ueW5ldDY2QGdtYWlsLmNvbSIsInByb2ZpbGVfaW1nIjoiaHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMC5nc3RhdGljLmNvbS9pbWFnZXM_cT10Ym46QU5kOUdjVGtZdnE3eldlWWdmMnlEeFBSRXhCay1sNGhoQ3prNkZ5aFdBJnVzcXA9Q0FVIiwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTcwODQyODkxNiwiZXhwIjoxNzA4NTMyNTk2fQ.H6-b-8GW25BbnZYJzSU1QsyuRXiIHkmcVFt14erqcfc

### Activate a user account
PUT http://localhost:3000/user/activate/38316fae-8574-426c-be71-56de9f85b170
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXRhaWxzIjp7ImlkIjoiYTkxNmUzMzQtY2JlOC00M2RhLWJmNmQtMGViNzM2YmUyZmMwIiwiZnVsbF9uYW1lIjoiYTkxNmUzMzQtY2JlOC00M2RhLWJmNmQtMGViNzM2YmUyZmMwIiwiZW1haWwiOiJrZW5ueW5ldDY2QGdtYWlsLmNvbSIsInByb2ZpbGVfaW1nIjoiaHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMC5nc3RhdGljLmNvbS9pbWFnZXM_cT10Ym46QU5kOUdjVGtZdnE3eldlWWdmMnlEeFBSRXhCay1sNGhoQ3prNkZ5aFdBJnVzcXA9Q0FVIiwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTcwODQyODkxNiwiZXhwIjoxNzA4NTMyNTk2fQ.H6-b-8GW25BbnZYJzSU1QsyuRXiIHkmcVFt14erqcfc

### Delete a user
DELETE   http://localhost:3000/user/delete/087d11c1-9fd7-4bae-b2c1-38119673146f

### Check user details
GET http://localhost:3000/user/details/user
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXRhaWxzIjp7ImlkIjoiYTkxNmUzMzQtY2JlOC00M2RhLWJmNmQtMGViNzM2YmUyZmMwIiwiZnVsbF9uYW1lIjoiYTkxNmUzMzQtY2JlOC00M2RhLWJmNmQtMGViNzM2YmUyZmMwIiwiZW1haWwiOiJrZW5ueW5ldDY2QGdtYWlsLmNvbSIsInByb2ZpbGVfaW1nIjoiaHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMC5nc3RhdGljLmNvbS9pbWFnZXM_cT10Ym46QU5kOUdjVGtZdnE3eldlWWdmMnlEeFBSRXhCay1sNGhoQ3prNkZ5aFdBJnVzcXA9Q0FVIiwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTcwODQxNDUyNiwiZXhwIjoxNzA4NTE4MjA2fQ.w54WWxuHYI8Y17VB0s8GwAKpI5XToRbrkM8pz74B5_g